version: "3.8"

services:
  app:
    build: ./docker
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: autorent
      MYSQL_USER: autorent
      MYSQL_PASSWORD: Parool123!
